title:              chitiibc
email:              your-email@example.com
description:        i post blockchain and cybersecurity usecased just for fun. 
author:             Rajesh Kalakoti
baseurl:            "/cyblock"
url:                "https://chittibc.github.io"

# Social Profiles
twitter_username: kalakotiRajesh
github_username: chittibc
facebook_username: kamal.rajesh.35
linkedin_username: rajesh-kalakoti-a75777117

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
